### ISSUE TITLE
ARM64 version of Hugo not installed on Apple silicon Mac

### ISSUE THREAD

**Issue by dboulet** [fenneclab/hugo-bin#123]
When using this package to install Hugo on a Mac with Apple silicon, the AMD64 version is installed instead of the ARM64 version which is built for Apple processors. This is because the [arch package](https://www.npmjs.com/package/arch) that this package ultimately depends on doesn’t properly detect ARM64 architecture on Apple silicon Macs, and reports it as being x64.

There is a pull request to fix this issue: https://github.com/feross/arch/pull/22.

**Comment by huima** [comment]
This is actually very strange as I today noticed similar problems.

1) Inside container that VsCode started I got x86 hugo instead of arm/linux hugo

2) on regular os x side I just got once a x68 binary and after removing node modules and running again it downlaoded the different one

First:

./node_modules/hugo-bin/vendor/hugo
zsh: exec format error: ./node_modules/hugo-bin/vendor/hugo
heimo.laukkanen@siilim210127 documentation % file ./node_modules/hugo-bin/vendor/hugo
./node_modules/hugo-bin/vendor/hugo: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, Go BuildID=047FzJlYdUNAPHE1vwdc/O5s3u9wN21tFgk-D3ycB/nnOcnhdYIE9_kD8-ifye/nOf4L01OOJQLNAr0cNgl, BuildID[sha1]=ed3eb0d1f5e08e8b048454e2898e96feae347258, stripped

Then:

file ./node_modules/hugo-bin/vendor/hugo
./node_modules/hugo-bin/vendor/hugo: Mach-O 64-bit executable x86_64

So it seems there is a possibility for more indeterministic results because of wrong recognition of correct platform.

**Comment by XhmikosR** [comment]
Please try with the latest version which updates Hugo to the latest version and uses universal binaries.

**Comment by dboulet** [comment]
This issue no longer applies. As of [Hugo v0.102.0](https://github.com/gohugoio/hugo/releases/tag/v0.102.0), it now uses a single universal binary that works on all Mac platforms.
